### ISSUE TITLE
How can i use this? I want to get a new username!

### ISSUE THREAD

**Issue by icidoug** [nbrylev/username-generator#1]

**Comment by AlmaPirata** [comment]
Sure, great soft, but didn't work on my mac (Catalina 10.15.3).
Please fix it!

**Comment by nbrylev** [comment]
@icidoug @AlmaPirata 
Wow guys, you are too fast. Stay connected and you will get a username generator soon.
(tbh didn't expect to see any issue here before realease)

**Comment by nbrylev** [comment]
@icidoug @AlmaPirata 
I've just released v.1.1.0, you can try it here - https://nbrylev.github.io/projects/username-generator/

I close this issue :)
